module CargoApp{

    interface cargo{
        boolean insertarCargo(in wstring codigo, in wstring nombre, in long sueldo);
        boolean actualizarCargo(in long idCargo,in wstring codigo, in wstring nombre, in long sueldo);
        boolean eliminarCargo(in long idCargo);

        oneway void shoutdown();

    };
};
