package provedorApp;


/**
* provedor/provedorInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from provedores.idl
* lunes 13 de mayo de 2019 04:49:37 PM COT
*/

abstract public class provedorInterfaceHelper
{
  private static String  _id = "IDL:provedor/provedorInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, provedorApp.provedorInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static provedorApp.provedorInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (provedorApp.provedorInterfaceHelper.id (), "provedorInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static provedorApp.provedorInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_provedorInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, provedorApp.provedorInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static provedorApp.provedorInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof provedorApp.provedorInterface)
      return (provedorApp.provedorInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      provedorApp._provedorInterfaceStub stub = new provedorApp._provedorInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static provedorApp.provedorInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof provedorApp.provedorInterface)
      return (provedorApp.provedorInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      provedorApp._provedorInterfaceStub stub = new provedorApp._provedorInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
