package provedorApp;


/**
* provedor/provedorInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from provedores.idl
* lunes 13 de mayo de 2019 04:49:37 PM COT
*/

public abstract class provedorInterfacePOA extends org.omg.PortableServer.Servant
 implements provedorApp.provedorInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarProvedor", new java.lang.Integer (0));
    _methods.put ("actualizarProvedor", new java.lang.Integer (1));
    _methods.put ("eliminarProvedor", new java.lang.Integer (2));
    _methods.put ("shoutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // provedor/provedorInterface/insertarProvedor
       {
         String nit = in.read_wstring ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         int telefono = in.read_long ();
         boolean $result = false;
         $result = this.insertarProvedor (nit, nombre, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // provedor/provedorInterface/actualizarProvedor
       {
         int idTablaProvedor = in.read_long ();
         String nit = in.read_wstring ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         int telefono = in.read_long ();
         boolean $result = false;
         $result = this.actualizarProvedor (idTablaProvedor, nit, nombre, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // provedor/provedorInterface/eliminarProvedor
       {
         int idTablaProvedor = in.read_long ();
         boolean $result = false;
         $result = this.eliminarProvedor (idTablaProvedor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // provedor/provedorInterface/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:provedor/provedorInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public provedorInterface _this() 
  {
    return provedorInterfaceHelper.narrow(
    super._this_object());
  }

  public provedorInterface _this(org.omg.CORBA.ORB orb) 
  {
    return provedorInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class provedorInterfacePOA
