package provedorApp;


/**
* provedor/provedorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from provedores.idl
* lunes 13 de mayo de 2019 04:49:37 PM COT
*/

public interface provedorInterfaceOperations 
{
  boolean insertarProvedor (String nit, String nombre, String direccion, int telefono);
  boolean actualizarProvedor (int idTablaProvedor, String nit, String nombre, String direccion, int telefono);
  boolean eliminarProvedor (int idTablaProvedor);
  void shoutdown ();
} // interface provedorInterfaceOperations
