package EmpleadoApp;


/**
* EmpleadoApp/_EmpleadoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* lunes 13 de mayo de 2019 02:04:39 PM COT
*/

public class _EmpleadoStub extends org.omg.CORBA.portable.ObjectImpl implements EmpleadoApp.Empleado
{

  public boolean insertarEmpleado (int cedula, String nombres, String apellidos, String cargo_id, String sucursal_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarEmpleado", true);
                $out.write_long (cedula);
                $out.write_wstring (nombres);
                $out.write_wstring (apellidos);
                $out.write_wstring (cargo_id);
                $out.write_wstring (sucursal_id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarEmpleado (cedula, nombres, apellidos, cargo_id, sucursal_id        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarEmpleado

  public boolean actualizarEmpleado (int idTablaEmpleado, int cedula, String nombres, String apellidos, String cargo_id, String sucursal_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarEmpleado", true);
                $out.write_long (idTablaEmpleado);
                $out.write_long (cedula);
                $out.write_wstring (nombres);
                $out.write_wstring (apellidos);
                $out.write_wstring (cargo_id);
                $out.write_wstring (sucursal_id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarEmpleado (idTablaEmpleado, cedula, nombres, apellidos, cargo_id, sucursal_id        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarEmpleado

  public boolean eliminarEmpleado (int idTablaEmpleado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarEmpleado", true);
                $out.write_long (idTablaEmpleado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarEmpleado (idTablaEmpleado        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarEmpleado

  public void shoutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shoutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shoutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shoutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EmpleadoApp/Empleado:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EmpleadoStub
