package EmpleadoApp;


/**
* EmpleadoApp/EmpleadoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* lunes 13 de mayo de 2019 02:04:39 PM COT
*/

public abstract class EmpleadoPOA extends org.omg.PortableServer.Servant
 implements EmpleadoApp.EmpleadoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEmpleado", new java.lang.Integer (0));
    _methods.put ("actualizarEmpleado", new java.lang.Integer (1));
    _methods.put ("eliminarEmpleado", new java.lang.Integer (2));
    _methods.put ("shoutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EmpleadoApp/Empleado/insertarEmpleado
       {
         int cedula = in.read_long ();
         String nombres = in.read_wstring ();
         String apellidos = in.read_wstring ();
         String cargo_id = in.read_wstring ();
         String sucursal_id = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarEmpleado (cedula, nombres, apellidos, cargo_id, sucursal_id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // EmpleadoApp/Empleado/actualizarEmpleado
       {
         int idTablaEmpleado = in.read_long ();
         int cedula = in.read_long ();
         String nombres = in.read_wstring ();
         String apellidos = in.read_wstring ();
         String cargo_id = in.read_wstring ();
         String sucursal_id = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarEmpleado (idTablaEmpleado, cedula, nombres, apellidos, cargo_id, sucursal_id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // EmpleadoApp/Empleado/eliminarEmpleado
       {
         int idTablaEmpleado = in.read_long ();
         boolean $result = false;
         $result = this.eliminarEmpleado (idTablaEmpleado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // EmpleadoApp/Empleado/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EmpleadoApp/Empleado:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Empleado _this() 
  {
    return EmpleadoHelper.narrow(
    super._this_object());
  }

  public Empleado _this(org.omg.CORBA.ORB orb) 
  {
    return EmpleadoHelper.narrow(
    super._this_object(orb));
  }


} // class EmpleadoPOA
