module productos {
    
    interface producto{
        boolean insertarProducto(in long codigo,in wstring nombre, in long cantidad, in long precio, in wstring provedores_nit, in wstring descripcion);
        boolean actualizarProducto(in long idTablaProducto,in long codigo,in wstring nombre, in long cantidad, in long precio, in wstring provedores_nit, in wstring descripcion);
        boolean eliminarProducto(in long idTablaProducto);
    };
};

