package sucursalApp;


/**
* sucursal/sucursalInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 04:49:48 PM COT
*/

public interface sucursalInterfaceOperations 
{
  boolean insertarSucursal (String nit, String nombre, String direccion, int telefono);
  boolean actualizarSucursal (int idSucursal, String nit, String nombre, String direccion, int telefono);
  boolean eliminarSucursal (int idSucursal);
  void shoutdown ();
} // interface sucursalInterfaceOperations
