package sucursalApp;


/**
* sucursal/sucursalInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 04:49:48 PM COT
*/

abstract public class sucursalInterfaceHelper
{
  private static String  _id = "IDL:sucursal/sucursalInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, sucursalApp.sucursalInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sucursalApp.sucursalInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sucursalApp.sucursalInterfaceHelper.id (), "sucursalInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sucursalApp.sucursalInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_sucursalInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sucursalApp.sucursalInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sucursalApp.sucursalInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sucursalApp.sucursalInterface)
      return (sucursalApp.sucursalInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sucursalApp._sucursalInterfaceStub stub = new sucursalApp._sucursalInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sucursalApp.sucursalInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sucursalApp.sucursalInterface)
      return (sucursalApp.sucursalInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sucursalApp._sucursalInterfaceStub stub = new sucursalApp._sucursalInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
