package sucursalApp;


/**
* sucursal/sucursalInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 04:49:48 PM COT
*/

public interface sucursalInterface extends sucursalInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface sucursalInterface
