package sucursalApp;


/**
* sucursal/sucursalInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 04:49:48 PM COT
*/

public abstract class sucursalInterfacePOA extends org.omg.PortableServer.Servant
 implements sucursalApp.sucursalInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarSucursal", new java.lang.Integer (0));
    _methods.put ("actualizarSucursal", new java.lang.Integer (1));
    _methods.put ("eliminarSucursal", new java.lang.Integer (2));
    _methods.put ("shoutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sucursal/sucursalInterface/insertarSucursal
       {
         String nit = in.read_wstring ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         int telefono = in.read_long ();
         boolean $result = false;
         $result = this.insertarSucursal (nit, nombre, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sucursal/sucursalInterface/actualizarSucursal
       {
         int idSucursal = in.read_long ();
         String nit = in.read_wstring ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         int telefono = in.read_long ();
         boolean $result = false;
         $result = this.actualizarSucursal (idSucursal, nit, nombre, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sucursal/sucursalInterface/eliminarSucursal
       {
         int idSucursal = in.read_long ();
         boolean $result = false;
         $result = this.eliminarSucursal (idSucursal);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // sucursal/sucursalInterface/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sucursal/sucursalInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public sucursalInterface _this() 
  {
    return sucursalInterfaceHelper.narrow(
    super._this_object());
  }

  public sucursalInterface _this(org.omg.CORBA.ORB orb) 
  {
    return sucursalInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class sucursalInterfacePOA
