package sucursalApp;

/**
* sucursal/sucursalInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 04:49:48 PM COT
*/

public final class sucursalInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public sucursalApp.sucursalInterface value = null;

  public sucursalInterfaceHolder ()
  {
  }

  public sucursalInterfaceHolder (sucursalApp.sucursalInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sucursalApp.sucursalInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sucursalApp.sucursalInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sucursalApp.sucursalInterfaceHelper.type ();
  }

}
