package productosApp;


/**
* productos/_productoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* lunes 13 de mayo de 2019 05:16:10 PM COT
*/

public class _productoStub extends org.omg.CORBA.portable.ObjectImpl implements productosApp.producto
{

  public boolean insertarProducto (int codigo, String nombre, int cantidad, int precio, String provedores_nit, String descripcion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarProducto", true);
                $out.write_long (codigo);
                $out.write_wstring (nombre);
                $out.write_long (cantidad);
                $out.write_long (precio);
                $out.write_wstring (provedores_nit);
                $out.write_wstring (descripcion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarProducto (codigo, nombre, cantidad, precio, provedores_nit, descripcion        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarProducto

  public boolean actualizarProducto (int idTablaProducto, int codigo, String nombre, int cantidad, int precio, String provedores_nit, String descripcion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarProducto", true);
                $out.write_long (idTablaProducto);
                $out.write_long (codigo);
                $out.write_wstring (nombre);
                $out.write_long (cantidad);
                $out.write_long (precio);
                $out.write_wstring (provedores_nit);
                $out.write_wstring (descripcion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarProducto (idTablaProducto, codigo, nombre, cantidad, precio, provedores_nit, descripcion        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarProducto

  public boolean eliminarProducto (int idTablaProducto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarProducto", true);
                $out.write_long (idTablaProducto);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarProducto (idTablaProducto        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarProducto

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:productos/producto:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _productoStub
