package productosApp;


/**
* productos/producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* lunes 13 de mayo de 2019 05:16:10 PM COT
*/

public interface producto extends productoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface producto
