package productosApp;


/**
* productos/productoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* lunes 13 de mayo de 2019 05:16:10 PM COT
*/

public interface productoOperations 
{
  boolean insertarProducto (int codigo, String nombre, int cantidad, int precio, String provedores_nit, String descripcion);
  boolean actualizarProducto (int idTablaProducto, int codigo, String nombre, int cantidad, int precio, String provedores_nit, String descripcion);
  boolean eliminarProducto (int idTablaProducto);
} // interface productoOperations
