package productosApp;

/**
* productos/productoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* lunes 13 de mayo de 2019 05:16:10 PM COT
*/

public final class productoHolder implements org.omg.CORBA.portable.Streamable
{
  public productosApp.producto value = null;

  public productoHolder ()
  {
  }

  public productoHolder (productosApp.producto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = productosApp.productoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    productosApp.productoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return productosApp.productoHelper.type ();
  }

}
