package productosApp;


/**
* productos/productoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* lunes 13 de mayo de 2019 05:16:10 PM COT
*/

abstract public class productoHelper
{
  private static String  _id = "IDL:productos/producto:1.0";

  public static void insert (org.omg.CORBA.Any a, productosApp.producto that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static productosApp.producto extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (productosApp.productoHelper.id (), "producto");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static productosApp.producto read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_productoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, productosApp.producto value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static productosApp.producto narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof productosApp.producto)
      return (productosApp.producto)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      productosApp._productoStub stub = new productosApp._productoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static productosApp.producto unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof productosApp.producto)
      return (productosApp.producto)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      productosApp._productoStub stub = new productosApp._productoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
