/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author USUARIO
 */
import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btnCargo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnSucursal = new javax.swing.JButton();
        btnProvedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCargo.setForeground(new java.awt.Color(60, 63, 65));
        btnCargo.setText("CARGO");
        btnCargo.setBorder(null);
        btnCargo.setBorderPainted(false);
        btnCargo.setContentAreaFilled(false);
        btnCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargoActionPerformed(evt);
            }
        });
        menu.add(btnCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 280, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/instrumentos.png"))); // NOI18N
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("MENU");
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(60, 63, 65));
        btnProductos.setText("PRODUCTOS");
        btnProductos.setBorder(null);
        btnProductos.setBorderPainted(false);
        btnProductos.setContentAreaFilled(false);
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        menu.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 340, -1, 50));

        btnEmpleado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(60, 63, 65));
        btnEmpleado.setText("EMPLEADO");
        btnEmpleado.setBorder(null);
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setContentAreaFilled(false);
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        menu.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 400, 130, 50));

        btnSucursal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSucursal.setForeground(new java.awt.Color(60, 63, 65));
        btnSucursal.setText("SUCURSAL");
        btnSucursal.setBorder(null);
        btnSucursal.setBorderPainted(false);
        btnSucursal.setContentAreaFilled(false);
        btnSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalActionPerformed(evt);
            }
        });
        menu.add(btnSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 460, 120, 50));

        btnProvedor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnProvedor.setForeground(new java.awt.Color(60, 63, 65));
        btnProvedor.setText("PROVEDOR");
        btnProvedor.setBorder(null);
        btnProvedor.setBorderPainted(false);
        btnProvedor.setContentAreaFilled(false);
        btnProvedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProvedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvedorActionPerformed(evt);
            }
        });
        menu.add(btnProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 520, 130, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 30, 30));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tornillo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 470, 540));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minimizar.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cerrar.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("FERRETERIA");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargoActionPerformed
       
        CargoForm objCargoForm = new CargoForm();
        objCargoForm.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnCargoActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        Empleado objEmpleado = new Empleado();
        objEmpleado.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvedorActionPerformed
        Provedor  objProvedor = new Provedor();
        objProvedor.setVisible(true);
        this.setVisible(false);     }//GEN-LAST:event_btnProvedorActionPerformed

    private void btnSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalActionPerformed
        Sucursal  objSucursal = new Sucursal();
        objSucursal.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_btnSucursalActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        Productos objProductos = new Productos();
        objProductos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //Cargo
        AnimationClass Cargo = new AnimationClass();
        Cargo.jButtonXRight(-130, 10, 10, 5, btnCargo);
        //<----
        AnimationClass Cargoo = new AnimationClass();
        Cargoo.jButtonXLeft(10, -130, 10, 5, btnCargo);
        //Producto        
        AnimationClass Producto = new AnimationClass();
        Producto.jButtonXRight(-130, 10, 10, 5, btnProductos);
        //<----
        AnimationClass Productoo = new AnimationClass();
        Productoo.jButtonXLeft(10, -130, 10, 5, btnProductos);
        //Empleado
        AnimationClass Empleado = new AnimationClass();
        Empleado.jButtonXRight(-130, 10, 10, 5, btnEmpleado);
        //<----
        AnimationClass Empleadoo = new AnimationClass();
        Empleadoo.jButtonXLeft(10, -130, 10, 5, btnEmpleado);
        //sucursal
        AnimationClass Sucursal = new AnimationClass();
        Sucursal.jButtonXRight(-130, 10, 10, 5, btnSucursal);
        //<----
        AnimationClass Sucursall = new AnimationClass();
        Sucursall.jButtonXLeft(10, -130, 10, 5, btnSucursal);
        //Provedores
        AnimationClass Provedor = new AnimationClass();
        Provedor.jButtonXRight(-130, 10, 10, 5, btnProvedor);
        //<----
        AnimationClass Provedorr = new AnimationClass();
        Provedorr.jButtonXLeft(10, -130, 10, 5, btnProvedor);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setState(CargoForm.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir del Menu","Exit", dialog);
        if (result == 0){
        System.exit(0);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargo;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProvedor;
    private javax.swing.JButton btnSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
