package CargoApp;


/**
* CargoApp/cargoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cargo.idl
* lunes 13 de mayo de 2019 02:04:11 PM COT
*/

abstract public class cargoHelper
{
  private static String  _id = "IDL:CargoApp/cargo:1.0";

  public static void insert (org.omg.CORBA.Any a, CargoApp.cargo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CargoApp.cargo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CargoApp.cargoHelper.id (), "cargo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CargoApp.cargo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_cargoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CargoApp.cargo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CargoApp.cargo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CargoApp.cargo)
      return (CargoApp.cargo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CargoApp._cargoStub stub = new CargoApp._cargoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CargoApp.cargo unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CargoApp.cargo)
      return (CargoApp.cargo)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CargoApp._cargoStub stub = new CargoApp._cargoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
