package CargoApp;


/**
* CargoApp/cargo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cargo.idl
* lunes 13 de mayo de 2019 02:04:11 PM COT
*/

public interface cargo extends cargoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cargo
