package CargoApp;


/**
* CargoApp/cargoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cargo.idl
* lunes 13 de mayo de 2019 02:04:11 PM COT
*/

public interface cargoOperations 
{
  boolean insertarCargo (String codigo, String nombre, int sueldo);
  boolean actualizarCargo (int idCargo, String codigo, String nombre, int sueldo);
  boolean eliminarCargo (int idCargo);
  void shoutdown ();
} // interface cargoOperations
